# Generated by Django 4.1.1 on 2022-09-06 11:30

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Defect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('form_ener', models.FloatField(verbose_name='Энергия образования вакансии')),
                ('mig_ener', models.FloatField(verbose_name='Энергия миграции вакансии')),
                ('dis_ener', models.FloatField(verbose_name='Энергия связи с дислокацией')),
                ('gr_ener', models.FloatField(verbose_name='Энергия связи с границей зерен')),
                ('tw_ener', models.FloatField(verbose_name='Энергия связи с границей двойников')),
                ('dis_svol', models.FloatField(verbose_name='Удел.объем области взаимодействия с дислокацией')),
                ('gr_svol', models.FloatField(verbose_name='Удел.объем области взаимодействия с границей зерей')),
                ('tw_svol', models.FloatField(verbose_name='Средний начальный диаметр кластера')),
                ('clus_init_diam', models.FloatField(verbose_name='Удел.объем области взаимодействия с границей двойников')),
                ('clus_init_count', models.FloatField(verbose_name='Средний начальное кол-во  v в кластере')),
                ('recomb_rad', models.FloatField(verbose_name='Радиус спонтанной рекомбинации')),
            ],
        ),
        migrations.CreateModel(
            name='ExperimentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warm_period', models.FloatField(verbose_name='Время нагрева на 1 К')),
                ('temp', models.FloatField(verbose_name='Температура во время эксперимента')),
            ],
        ),
        migrations.CreateModel(
            name='Metal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Имя металла')),
                ('gr_sarea', models.FloatField(verbose_name='Удельная площадь границ зерен')),
                ('tw_sarea', models.FloatField(verbose_name='Удельная площадь границ двойников')),
                ('dis_dens', models.FloatField(verbose_name='Плотность дислокаций')),
                ('grid_par', models.FloatField(verbose_name='Параметр решетки')),
                ('close_node', models.FloatField(verbose_name='Расстояние до ближайшего узла')),
            ],
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(default=datetime.datetime.utcnow, verbose_name='время эксперимента')),
                ('defect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calcapp.defect', verbose_name='характеристики ТД')),
                ('exp_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calcapp.experimentsettings', verbose_name='характеристики ТД')),
                ('metal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calcapp.metal', verbose_name='металл')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiment', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
