# Generated by Django 4.1.1 on 2022-09-06 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='defect',
            options={'verbose_name': 'характеристика ТД', 'verbose_name_plural': 'характеристики ТД'},
        ),
        migrations.AlterModelOptions(
            name='experimentsettings',
            options={'verbose_name': 'условия эксперимента', 'verbose_name_plural': 'условия эксперимента'},
        ),
        migrations.AlterModelOptions(
            name='metal',
            options={'verbose_name': 'металл', 'verbose_name_plural': 'металлы'},
        ),
        migrations.AddField(
            model_name='experimentsettings',
            name='name',
            field=models.CharField(default=1, max_length=30, verbose_name='Название'),
            preserve_default=False,
        ),
    ]
