# Generated by Django 4.1.1 on 2022-12-08 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcapp', '0004_rename_name_defect_defect_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimentsettings',
            name='temp_delta',
            field=models.FloatField(default=1, verbose_name='Шаг в К'),
        ),
    ]
