# Generated by Django 4.1.1 on 2022-12-08 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calcapp', '0005_experimentsettings_temp_delta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experimentsettings',
            old_name='temp_delta',
            new_name='temp_step',
        ),
    ]
