# Generated by Django 4.1.1 on 2022-12-22 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcapp', '0006_rename_temp_delta_experimentsettings_temp_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimentsettings',
            name='time_step',
            field=models.FloatField(default=60, verbose_name='Шаг в секундах'),
        ),
    ]
