# Generated by Django 4.1.1 on 2022-12-22 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcapp', '0007_experimentsettings_time_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimentsettings',
            name='conc_vac_start',
            field=models.FloatField(default=0.00046, verbose_name='Начальная концентрация вакансий'),
        ),
    ]
