# Generated by Django 4.1.1 on 2022-12-25 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcapp', '0008_experimentsettings_conc_vac_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='defect',
            name='surf_ener',
            field=models.FloatField(default=0.85, verbose_name='Энергия связи с поверхностью'),
        ),
        migrations.AddField(
            model_name='defect',
            name='surf_svol',
            field=models.FloatField(default=2.2e-07, verbose_name='Удел.объем области для поверхности'),
        ),
        migrations.AlterField(
            model_name='experimentsettings',
            name='temp_step',
            field=models.FloatField(default=1, verbose_name='Шаг в К (НЕ ИСПОЛЬЗУЕТСЯ!!)'),
        ),
    ]
