# Generated by Django 4.1.1 on 2022-12-27 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calcapp', '0009_defect_surf_ener_defect_surf_svol_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defect',
            name='dis_svol',
        ),
        migrations.RemoveField(
            model_name='defect',
            name='gr_svol',
        ),
        migrations.RemoveField(
            model_name='defect',
            name='tw_svol',
        ),
    ]
