# Generated by Django 4.1.1 on 2022-12-27 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcapp', '0011_remove_experimentsettings_temp_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defect',
            name='clus_init_count',
            field=models.FloatField(verbose_name='Среднее начальное кол-во  v в кластере'),
        ),
        migrations.AlterField(
            model_name='defect',
            name='clus_init_diam',
            field=models.FloatField(verbose_name='Средний начальный диаметр кластера, м'),
        ),
        migrations.AlterField(
            model_name='defect',
            name='dis_ener',
            field=models.FloatField(verbose_name='Энергия связи с дислокацией, эВ'),
        ),
        migrations.AlterField(
            model_name='defect',
            name='form_ener',
            field=models.FloatField(verbose_name='Энергия образования вакансии, эВ'),
        ),
        migrations.AlterField(
            model_name='defect',
            name='gr_ener',
            field=models.FloatField(verbose_name='Энергия связи с границей зерен, эВ'),
        ),
        migrations.AlterField(
            model_name='defect',
            name='mig_ener',
            field=models.FloatField(verbose_name='Энергия миграции вакансии, эВ'),
        ),
        migrations.AlterField(
            model_name='defect',
            name='recomb_rad',
            field=models.FloatField(verbose_name='Радиус спонтанной рекомбинации, м'),
        ),
        migrations.AlterField(
            model_name='defect',
            name='surf_ener',
            field=models.FloatField(default=0.85, verbose_name='Энергия связи с поверхностью, эВ'),
        ),
        migrations.AlterField(
            model_name='defect',
            name='tw_ener',
            field=models.FloatField(verbose_name='Энергия связи с границей двойников, эВ'),
        ),
        migrations.AlterField(
            model_name='experimentsettings',
            name='temp_start',
            field=models.FloatField(verbose_name='Температура в начале эксперимента, К'),
        ),
        migrations.AlterField(
            model_name='experimentsettings',
            name='temp_stop',
            field=models.FloatField(verbose_name='Температура в конце эксперимента, К'),
        ),
        migrations.AlterField(
            model_name='experimentsettings',
            name='time_step',
            field=models.FloatField(default=60, verbose_name='Шаг, с'),
        ),
        migrations.AlterField(
            model_name='experimentsettings',
            name='warm_period',
            field=models.FloatField(verbose_name='Время нагрева на 1 К, с'),
        ),
        migrations.AlterField(
            model_name='metal',
            name='close_node',
            field=models.FloatField(verbose_name='Расстояние до ближайшего узла, м'),
        ),
        migrations.AlterField(
            model_name='metal',
            name='dis_dens',
            field=models.FloatField(verbose_name='Плотность дислокаций, м-2'),
        ),
        migrations.AlterField(
            model_name='metal',
            name='gr_sarea',
            field=models.FloatField(verbose_name='Удельная площадь границ зерен, м-1'),
        ),
        migrations.AlterField(
            model_name='metal',
            name='grid_par',
            field=models.FloatField(verbose_name='Параметр решетки, м'),
        ),
        migrations.AlterField(
            model_name='metal',
            name='tw_sarea',
            field=models.FloatField(verbose_name='Удельная площадь границ двойников, м-1'),
        ),
    ]
