# Generated by Django 4.1.1 on 2023-05-23 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calcapp', '0014_metal_atomic_volume_metal_metal_length_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defect',
            name='recomb_rad',
        ),
        migrations.RemoveField(
            model_name='metal',
            name='metal_length',
        ),
    ]
